-- Create the user_data table if it doesn't exist
create table if not exists public.user_data (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null unique,
  data jsonb default '{}'::jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.user_data enable row level security;

-- Create Policy: Users can only see and edit their own data
create policy "Users can all their own data" 
  on public.user_data 
  for all 
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Enable Realtime for this table
alter publication supabase_realtime add table user_data;
